id = "yaml-sql"
name = "YAML SQL"
version = "0.0.1"
schema_version = 1
authors = ["Tin Trinh"]
description = "YAML support with SQL syntax injections for annotated or sql-named values."
repository = "https://github.com/tinwonda/zed-yaml-sql-language-support"

[grammars.yaml]
repository = "https://github.com/zed-industries/tree-sitter-yaml"
commit = "f545a41f57502e1b5ddf2a6668896c1b0620f930"

[grammars.sql]
repository = "https://github.com/DerekStride/tree-sitter-sql"
commit = "4a99c73f5384f2be10adc55208c84d95a7eb1137"
